version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: capstone
      DB_USER: cap_user
      DB_PASS: cap_pass
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: capstone
      MYSQL_USER: cap_user
      MYSQL_PASSWORD: cap_pass
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: